use (
  {AssertionError} = dep://assert
  {assert} = dep://chai
  expected = ~
)

suite(__filename, proc()
  suite("toBeCallable()", proc()
    test("when values are callable, wrapper must be returned", proc()
      # (1) act
      const (
        w = expected(x = nop, y = nop, z = nop).members("x", "y")
        out = w.toBeCallable()
      )

      # (2) assessment
      assert.strictEqual(w, out)
    end)

    test("when some value is not callable, assertion error must be raised", proc()
      # (1) act
      const out = peval(expected(x = nop, y = "", z = nop).members("x", "y").toBeCallable())

      # (2) assessment
      assert.equal(out[0], false)
      assert.instanceOf(out[1], AssertionError)
      assert.include(out[1].message, "should be callable")
    end)
  end)

  suite("notToBeCallable()", proc()
    test("when values are not callable, wrapper must be returned", proc()
      # (1) act
      const (
        w = expected(x = "", y = "", z = "").members("x", "y")
        out = w.notToBeCallable()
      )

      # (2) assessment
      assert.strictEqual(w, out)
    end)

    test("when some value is callable, assertion error must be raised", proc()
      # (1) act
      const out = peval(expected(x = "", y = nop, z = "").members("x", "y").notToBeCallable())

      # (2) assessment
      assert.equal(out[0], false)
      assert.instanceOf(out[1], AssertionError)
      assert.include(out[1].message, "should not be callable")
    end)
  end)
end)
